name: Install Laravel Nova

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Which version of Laravel Nova to install'
        required: true
        default: '4'
        type: choice
        options:
          - '4'
          - '3'

jobs:
  test_php_workflow:
    runs-on: ubuntu-22.04

    name: Name of job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none

      - name: Setup Laravel Nova 3 (Orion)
        if: inputs.version == '3'
        uses: ./.github/workflows/actions/laravel-nova
        with:
          username: ${{ secrets.NOVA_3_USERNAME }}
          password: ${{ secrets.NOVA_3_PASSWORD }}

      - name: Setup Laravel Nova 4 (Silver Surfer)
        if: inputs.version == '4'
        uses: ./.github/workflows/actions/laravel-nova
        with:
          username: ${{ secrets.NOVA_4_USERNAME }}
          password: ${{ secrets.NOVA_4_PASSWORD }}
