# Ensures every pull request has a label when a pull request is opened, reopened or is updated with a new commit.

name: Pull Requests

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  label_pull_request:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      pull-requests: write

    name: Label Pull Request
    uses: verplankedev/.github/.github/workflows/pull-requests.yml@main

    steps:
      - name:
      - uses: release-drafter/release-drafter@v6
        with:
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
