name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE by @$AUTHOR in [#$NUMBER]($URL)'

template: |
  $CHANGES

footer: |  
  $CONTRIBUTORS

categories:
  - title: 'Features'
    label: 'feature'

  - title: 'Fixes'
    label: 'fix'

  - title: 'Chores'
    label: 'chore'

autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/chore\/.+/'

  - label: 'fix'
    branch:
      - '/fix\/.+/'
      - '/hotfix\/.+/'

  - label: 'feature'
    branch:
      - '/feat\/.+/'
      - '/feature\/.+/'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'fix'
      - 'chore'
  default: minor
