name: 'Setup Laravel Nova'
description: 'Setup Laravel Nova for installation'
inputs:
  username:
    description: 'Nova username'
    required: true
  password:
    description: 'Nova license key (password)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Composer
      shell: bash
      run: composer config "http-basic.nova.laravel.com" "${{ inputs.username }}" "${{ inputs.password }}"
