# Draft a new release or updates the drafted release when there is a push event to the main branch.

name: Draft Release

on:
  # workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  draft_release:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          publish: true
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
