name: Test PHP Workflow

on:
  workflow_dispatch:
    version:
      description: 'Which version of Laravel Nova to install'
      required: true
      default: '4'
      type: choice
      options:
        - '4'
        - '3'

jobs:
  test_php_workflow:
    runs-on: ubuntu-22.04

    name: Name of job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none

      - name: Install Laravel Nova
        # if: matrix.php >= 8.2
        uses: ./actions/.github/workflows/actions/laravel-nova
        with:
          version: ${{ inputs.version }}
