# This workflow ensures every pull request has a label
# when a pull request is opened, reopened or is updated with a new commit.

name: Pull Requests

on:
  # workflow_call:
  workflow_dispatch:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  draft_release:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
