name: Post Release

on:
  workflow_call:
    secrets:
      RELEASE_TOKEN:
        description: 'Personal Access Token for creating a release at Github'
        required: false

jobs:
  github:
    if: ${{ github.ref == 'refs/heads/main' }} # guard, only run workflow on main branch

    runs-on: ubuntu-22.04

    name: Github Release

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        run: npm i -D semantic-release conventional-changelog-conventionalcommits

      - name: Publish Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # defined at ORG level at Github
        run: npx semantic-release

  sentry:
    needs: github

    runs-on: ubuntu-22.04

    name: Sentry Release

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish Sentry Release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }} # defined at ORG level at Github
          SENTRY_ORG: ${{ vars.SENTRY_ORG }} # defined at ORG level at Github
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }} # defined at REPO level at Github
        with:
          environment: production
          version: ${{ github.event.release.tag_name }}

  update_changelog:
    needs: github

    runs-on: ubuntu-22.04

    permissions:
      contents: write

    name: Update Changelog

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.target_commitish }}

      - name: Extract release date from git tag
        id: release_date
        run: |
          echo "date=$(git log -1 --date=format:%d-%m-%Y --pretty=format:%ad '${{ github.event.release.tag_name }}')" >> $GITHUB_OUTPUT;

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          release-date: ${{ steps.release_date.outputs.date }}
          release-notes: ${{ github.event.release.body }}
          latest-version: ${{ github.event.release.tag_name }}
          compare-url-target-revision: ${{ github.event.release.target_commitish }}
          parse-github-usernames: true

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

