name: Release Drafter

on:
  # workflow_call:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  draft_release:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: release-drafter/release-drafter@v6
#        with:
#          publish: true
#        with:
#          publish: ${{ steps.check-version.outputs.tag != '' }}
#          tag: ${{ steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_DRAFTER_TOKEN }}
